image: docker:24

pipelines:
  default:
    - step:
        name: Docker Build & Push
        services:
          - docker
        script:
          - export DOCKER_BUILDKIT=0
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          - docker build -t viddeveloper1/buynest-frontend:latest .
          - docker push viddeveloper1/buynest-frontend:latest

definitions:
  services:
    docker:
      memory: 3072
